import type { Metadata } from 'next';
import '@/css/common.scss';
import '@/css/reset.scss';
import './product.scss';
import StyledComponentsRegistry from '@/registry';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**  项目根布局  */
export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
